// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8UF1UNXL1g5-3U5CJi7QwJxTPOUsEjyQ',
    appId: '1:723047128823:web:e7836b7f716cac0eb83df2',
    messagingSenderId: '723047128823',
    projectId: 'ahli-gigi-acenk',
    authDomain: 'ahli-gigi-acenk.firebaseapp.com',
    storageBucket: 'ahli-gigi-acenk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7tbMZnKUGme_rLKOB3bRnsFaBkEaPqI4',
    appId: '1:723047128823:android:21aa408d5df132bbb83df2',
    messagingSenderId: '723047128823',
    projectId: 'ahli-gigi-acenk',
    storageBucket: 'ahli-gigi-acenk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYhAhCrZOo-epDLzra-gkUwQSO1b36mWk',
    appId: '1:723047128823:ios:0d80c8bd5a7e2e89b83df2',
    messagingSenderId: '723047128823',
    projectId: 'ahli-gigi-acenk',
    storageBucket: 'ahli-gigi-acenk.appspot.com',
    androidClientId: '723047128823-o5m93l7m7gths47g3lm1gd5uq86d7121.apps.googleusercontent.com',
    iosClientId: '723047128823-1uau1vd5gdser8ebsmtdufoqc261o59a.apps.googleusercontent.com',
    iosBundleId: 'com.example.ahliGigi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYhAhCrZOo-epDLzra-gkUwQSO1b36mWk',
    appId: '1:723047128823:ios:0d80c8bd5a7e2e89b83df2',
    messagingSenderId: '723047128823',
    projectId: 'ahli-gigi-acenk',
    storageBucket: 'ahli-gigi-acenk.appspot.com',
    androidClientId: '723047128823-o5m93l7m7gths47g3lm1gd5uq86d7121.apps.googleusercontent.com',
    iosClientId: '723047128823-1uau1vd5gdser8ebsmtdufoqc261o59a.apps.googleusercontent.com',
    iosBundleId: 'com.example.ahliGigi',
  );
}
